import Head from "next/head"
import { useState, useEffect } from "react"

export default function Home() {
  const [data, setData] = useState()
  const [isLoading, setLoading] = useState(true)
  const [currentMeme, setCurrentMeme] = useState(Math.floor(Math.random() * 20))

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch("https://api.imgflip.com/get_memes")
      const data = await res.json()
      setData(data)
      setLoading(false)
    }

    fetchData()
  }, [])

  return (
    <>
      <Head>
        <title>meme generator :)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <header className=" mt-8">
          <p className="font-extrabold text-2xl"> Meme Template Generator</p>
          <p className="max-w-sm">
            A meme template generator. May break if you click the generate meme
            button too fast. Wait about 1-2 seconds between each meme.
          </p>
        </header>
        {data && (
          <div className="m-4 border-2 border-black rounded-xl p-2">
            <img
              src={data.data.memes[currentMeme].url}
              alt=""
              width={340}
              className="border-2 border-black rounded-lg mb-2"
            />
            <p className="text-xl max-w-xl italic">
              {data.data.memes[currentMeme].name}
            </p>
            <a
              href={data.data.memes[currentMeme].url}
              download
              className="text-blue-700 underline active:text-red-800"
            >
              download
            </a>
          </div>
        )}
        <p className="m-2 max-w-lg"> {isLoading && "loading..."} </p>
        <button
          className="bg-emerald-500 text-white p-2 rounded hover:opacity-90 active:opacity-60 font-medium "
          onClick={() => {
            setCurrentMeme(
              Math.floor(Math.random() * data.data.memes.length - 1)
            )
          }}
        >
          Generate Meme
        </button>{" "}
      </main>
    </>
  )
}
